### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by godrei** [bitrise-io/devcenter#159]
Broken link at: devcenter/docs/faq/github-pull-request-status-troubleshooting.md

If you can't see the nice little green/red CI checks status (like the one you can see on our [Blog,
about the Pull Request status feature announcement](http://blog.bitrise.io/2015/04/23/pull-request-support-for-github-repositories.html))
on the Pull Request's GitHub page, you should check this list for troubleshooting.

**Comment by viktorbenei** [comment]
Fixed in https://github.com/bitrise-io/devcenter/pull/160
