### ISSUE TITLE
faq links are out of date

### ISSUE THREAD

**Issue by pfaucon** [bitrise-io/devcenter#161]
https://raw.githubusercontent.com/bitrise-io/devcenter/master/docs/faq/why-my-build-takes-longer-on-bitrise-than-on-my-mac.md 

links to:

/faq/should-i-commit-my-dependencies-into-my-repository

should link to:

**/docs**/faq/should-i-commit-my-dependencies-into-my-repository

It appears that there[ a few occurrences of the same issue](https://github.com/bitrise-io/devcenter/search?utf8=%E2%9C%93&q=%2Ffaq%2F&type=), but they should be easy to fix

**Comment by slapec93** [comment]
Thank you for your notice. These links concern the http://devcenter.bitrise.io/ page, which has the `docs` folder as root, so the `docs/` folder isn't needed in the links. If you check the actual links at http://devcenter.bitrise.io/ they work fine and point to the correct .md files :)

**Comment by viktorbenei** [comment]
Indeed, thanks @slapec93 & @pfaucon ! :)

Just a question @pfaucon : where did you saw the broken links? Here on GitHub? We definitely should highlight this better, that the links are for http://devcenter.bitrise.io - do you have a recommendation where we should put this? Just into the README? Would that help you @pfaucon ?

**Comment by pfaucon** [comment]
That makes sense, and yes it looks like the links work fine from  http://devcenter.bitrise.io.  Perhaps a reference to  http://devcenter.bitrise.io in the README would be helpful, although I only ended up here from a (probably old?) forum post, so it probably won't be a problem for most people.

**Comment by viktorbenei** [comment]
Sorry for the inconvenience @pfaucon and thanks for the info!

Do you know which blog post it was?

We'll add the link to the README in any case ;)

**Comment by viktorbenei** [comment]
Added to the README in https://github.com/bitrise-io/devcenter/pull/163

@pfaucon let us know if you'd change the text in any way!
