### ISSUE TITLE
Unavailable images hosted on filepicker.io

### ISSUE THREAD

**Issue by koral--** [bitrise-io/devcenter#199]
E.g. on this page: https://devcenter.bitrise.io/adding-a-new-app/setting-up-ssh-keys/ there is an image loaded from: https://www.filepicker.io/api/file/z78ihfOER2yFsN3Mhuvn but the last URL does not point to the image but to plain text `Application AINx3Px6wQsi3DiI4lSOHz is unavailable`

**Comment by viktorbenei** [comment]
Thanks for reporting @koral-- !

@annabatki can you please check this?

**Comment by annabatki** [comment]
Thanks, @koral-- , I had this on my to-do-list two weeks ago, then mysteriously the images were online last week. Luckily I saved them then, so now I've replaced them. This is better this way. :)
